<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyTitle>Fantaseer.HDT</AssemblyTitle>
		<TargetFramework>net472</TargetFramework>
		<LangVersion>Latest</LangVersion>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
		<OutputType>Library</OutputType>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<ComVisible>false</ComVisible>
		<Platforms>x86</Platforms>							
		<Guid>ee465e91-527c-11f1-919e-c2b62456cdd1</Guid>
		<Configurations>Debug;Release;Plugin</Configurations>
	</PropertyGroup>
	<PropertyGroup>
		<!-- Assembly Information -->
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)' == 'Plugin'">
		<OutputPath>C:\Users\ezexey\AppData\Roaming\HearthstoneDeckTracker\Plugins</OutputPath>
	</PropertyGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.InteropServices.GuidAttribute">
			<_Parameter1>$(Guid)</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Fantaseer\Fantaseer.csproj" />

		<ProjectReference Include="E:\source\Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\Hearthstone Deck Tracker.csproj">
			<Private>False</Private>
			<CopyLocalSatelliteAssemblies>False</CopyLocalSatelliteAssemblies>
			<ExcludeAssets>runtime</ExcludeAssets>
		</ProjectReference>
		<ProjectReference Include="E:\source\Hearthstone-Deck-Tracker\HearthWatcher\HearthWatcher.csproj">
			<Private>False</Private>
			<ExcludeAssets>runtime</ExcludeAssets>
		</ProjectReference>
		<Reference Include="HearthDb">
			<HintPath>E:\source\Hearthstone-Deck-Tracker\lib\HearthDb.dll</HintPath>
			<Private>False</Private>
			<CopyLocalSatelliteAssemblies>False</CopyLocalSatelliteAssemblies>
			<ExcludeAssets>runtime</ExcludeAssets>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\Stringz.Designer.cs">
			<DependentUpon>Stringz.resx</DependentUpon>
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
		</Compile>
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Update="Properties\Stringz.resx">
			<LastGenOutput>Stringz.Designer.cs</LastGenOutput>
			<Generator>ResXFileCodeGenerator</Generator>
		</EmbeddedResource>
	</ItemGroup>
</Project>
