<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyTitle>Fantaseer</AssemblyTitle>
		<TargetFramework>net472</TargetFramework>
		<LangVersion>Latest</LangVersion>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
		<OutputType>Library</OutputType>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<Platforms>x64</Platforms>
		<Guid>4a96aa55-527b-11f1-95ea-16c0c897d3f1</Guid>
		<Configurations>Debug;Release;Pre</Configurations>
	</PropertyGroup>
	
	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.InteropServices.GuidAttribute">
			<_Parameter1>$(Guid)</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="System.Net.Http" Version="4.3.4" />
		<PackageReference Include="System.Text.Json" Version="10.0.3" /> 
		<Reference Include="System.Web" />
	</ItemGroup>
</Project>